### ISSUE TITLE
reddit mobber :*

### ISSUE THREAD

**Issue by pythonGui** [SavannahCatToken/Pancakeswap_BSC_Sniper_Bot_Fullversion#1]
dont download hack script !!!!!!!!!!!!!!!!!

**Comment by reuniware** [comment]
Can you give more details please ?

**Comment by jontstaz** [comment]
Can you please paste the malicious code snippet in your issue?

I've had a cursory look at the code and so far I've found nothing malicious. I've been looking primarily at the "txns.py" file to see if he is replacing the Token's contract address with his personal address and looking for the same thing in "Sniper.py" and the 2 files in the "abis" folder. I found nothing malicious or any evidence that this is a "hack".

I have no vested interest in this project, I've never even used it so I'm unbiased. I'd like to see some evidence from you however

Cheers

**Comment by reuniware** [comment]
Thanks !

**Comment by SavannahCatToken** [comment]
TF this is not an hack I code this from an open source code. I'm working on updates but unfortunately I can't work fast enough if you have corona and were in the intensive care unit!

Show me the "Hack" 

just because the tax (remuneration) is my address is it supposed to be a hack? it is even written in the scrypt 0.7% TAX

Thanks for reading
